services:
  web:
    build: ./web
    volumes:                                                                          # Danh sách dự án đưa vào VM
      - ../autotradebot:/var/www/html/bibobot
      - ../getPriceBot:/var/www/html/getPriceBot
      # - ../laravel:/var/www/html/laravel

      - ./web/config/vhost.conf:/etc/apache2/sites-available/000-default.conf         # Thiết lập Virtual Host
      - ./web/ssl:/etc/ssl/lunglinhlenluon.com                    # Danh sách file cấu hình ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  db:
    build: ./mysql
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: "phanquan1808"
    volumes:
      - ./mysql/data:/var/lib/mysql                                               # Lưu db                
      - ./mysql/ibdata:/data/mysql                                                # Lưu db 
      - ./mysql/init:/data/init                                                   # Path chứa seeder
    ports:
    - 3306:3306
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
